services:
  postgres:
    image: postgres:15-alpine
    container_name: dungeon-game-postgres
    environment:
      POSTGRES_DB: dungeon_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dungeon_game"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  dungeon-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dungeon-game-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dungeon_game
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy